### ISSUE TITLE
HLAE Error While Launching CS:GO.

### ISSUE THREAD

**Issue by vivdas** [advancedfx/advancedfx#149]
```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```
IMAGE OF THE ERROR: https://i.imgur.com/qgZNyyO.png

**Comment by dtugend** [comment]
```
ERROR_ACCESS_DENIED

    5 (0x5)

    Access is denied.
```

Please make sure that no Anit-Cheat Client like ESEA Client, Faceit Client / Challengeme.gg is running before launching CS:GO from HLAE.

**Comment by dtugend** [comment]
Closing due to lacking feedback.
