### ISSUE TITLE
Error code 2001 when loading DLL

### ISSUE THREAD

**Issue by Sparkk21** [advancedfx/advancedfx#421]
Every time I try to load the AfxHookSource DLL in the custom loader, I get an error that says Loader Failed with Code: 2001, and it says this in the description: 

> System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)

RESOLVED: I somehow fixed it by selecting the csgo.exe, even though that didn't work before -_-

**Comment by dtugend** [comment]
Closing since you fixed it already (path must end with `\csgo.exe`).
