### ISSUE TITLE
error message when attempting to launch CS:GO through HLAE

### ISSUE THREAD

**Issue by lauknload** [advancedfx/advancedfx#86]
Here is my error message:

```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```
Thanks

**Comment by dtugend** [comment]
1) Make sure that neither csgo.exe nor HLAE.exe nor Steam.exe are set to run as admin.
2) Make sure that no Anit Cheat (ESEA Client / FaceIt Client / ChallengeMe.gg) is running when launching from HLAE.

**Comment by lauknload** [comment]
Yeah, it was my FaceIt anticheat looks like. Thanks!
